# Generated by Django 4.2.16 on 2024-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joiningdate',
            field=models.DateField(max_length=50),
        ),
    ]
